language: ruby
rvm:
- 2.0.0
#branches:
#  only:
#  - master
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
env:
  global:
  - secure: NAsbGFwyTEbbrXqym4pgd72oFRXTJWz/75HyPvm5Oi+aWRyEiTCe666yxgAfbNr5hd8ipGirDDTwJF+nXB5pqS75iT6MQ/VQ7hAhbP9a6hKSu42ZW/4xNEIDYUW88tBRJkUVNhgJzRdmYJRWt/G9wy0VoZE5SWLVSlZCebiC5wsS+8xV5qkj8RRmXogoyFSfsrvBtuo8wPZq3+UU5nhnFOBsgyO/BrZ2FgNGBq4904Tg/u0PTVLV6ePwjurZC9yUI90c/5RtD2Apd22BX6Hn+XrbHu0bqezR2Ux4xoKPWzgTnqvAClACDXbKMy+n1zWJMojEEoN+T3vOKHxM4zBRALi6Mwt0ZDPnT+i6EWgU3GdzF8Z+d6YiKgoRw+G3NUkYf86uCVZrP72RcCVJEywJ/Gfzdpq8gIjfwQThTqjj6CxpaTY0QfrfNCLb1xgRNw7+TaFuB5ZdbnLXh05cFZh5R7Av4IcQkfpP2WxwIbi88/5uHZkhWjCGsXFW/qdv/rkXE+s5MhbTG8LEFktdKVxQs9xkBdCXKamW2B840ehgxdZldEgDRcN7Bff6mHk5r66g1/xVfHJt+IifjK4bqB6CQL/BxTXuNb7v4JRn+k5NsMuPI4QO8jLYCwcLTUAaW2ohxQuYOA/Avn5GIc9aWARcWCasGO7bKOKREwW8EM4iyWI=
  - secure: L8RxIjDEjw+3Rze/7/f0JukzD9/F3whJcAt21+29lwQfMWT0NcFmm1bTHWad2BRCy6Pgh1VsbCuy/k+3TBuzt/rM9cv5X3onddNx1Y++kTTGbJRio7Ml/VR/xdPr6uqSbJCsWdV1RhfOx2lyJa2+li3JuDRitZFzol2NBdHMUbIbn/L2N3e1iIvjU+eK7bR7cCgzXnOQ1dh+LQ8Z8XFfY6rK5CcKpV1wEYyxNuQE2EbcTkdzqn3eqGCJ7cWaqp4nBmjPHw6CE1sXDidFfdh86dpXTHLjQOAGf5o0yAwpadIRIp2yEAYDzWvQUOarqXwFXjdDh0DmeWmV2tB9Hdwdguo1fV9WFydEtbkFuhZIF3Rchblg0V26mRyiCA2K9tOdWuPz9UJPBYaUgLGziJ8fzu89+C1dz5Mzme7KE6lnJoT6R5phN+Jh0muz1FwDQNoR6UFEZ/o0eOOBKLZUuKnIN05lFpMF8Qf/RBPc/0oORr9Q4GG0MqxLb5/3tYpHf7AtDOo3/ifPdExISIVVkf/lYXPDESNckvnD3ZCx+q8PwBd5EKD3DhOB72VWLNGZLD34KP58n2ajaMnLxmytMmhg7/1V9oyVmYmp8tDk6Xa3sQAMMwO5jGEJbiw14we/QJDhIGRw9XC7PhGdpm7VpVTzAdrrnyqmF89H1iiKMVdWLDo=
