language: ruby
rvm:
- 2.0.0
branches:
  only:
  - master
script: bundle exec jekyll build
install: bundle install
deploy:
  provider: s3
  access_key_id:
    secure: mwTo9YTyPA6kyPWcGOt02s8kapASS/IvyVu0OwLs8tj/6obcYZB7kvELvO0z4fMqb+FvjxJfqllM2YxXwWmZJOb8cIIkEz/BuogFLu+BopMhz9AvCShq3sCXqb+QnuUEJKwlSuFSTDSpZlvZLoc3P7P9hL8HZwhPvra8TVznml0UbVcfBr0lyjRr0N5749XcBQPq5132BpDsUPqm90meyXYxpsS3U+492UEaG6EP6ar9/fH/G3fSGGm/jvE3lZEuXkIzWJgpvQakmofk+hcaVDAe0LbbbUkEodBiPBuiib8PRYoJGHIaZinRcP0yIDiYrswUC56XdQhZ4JIXgSFMaGXXeaiuhEbT+nzio2VZxAeW//l6hUzkNF2N/QK4dOPB8trM4B0hfWBhfW32G6gjqy36s4vbxIU53G/DSN4S6yj4BKa39sqMxgflBwYNrjAYpXyFJrJOJMF3QntGZ51qbqD5QdLMwNi/mDVIiW7inAMVRSNHOBo5Ef9nByyNIni5JyZo6n/1khbqVNkJc71JdoOhmevhyP1mTNil7/uf4+3D1/yCkeMpyzIC4x5hoX2ASaFKls/4dybyqcz3SlX9VsFJxEbPFmk6f2PP3e6pTXAMc3nD3lgihQxCUz5sX6dnDE17EU6+cCT6b49CuNo9+IFvCl14BVU+6MUzNZrz2hc=
  secret_access_key:
    secure: f31R+LdgzU7zSBFQ1Rd+j+ennyevLILLWFd+tbm6flP2/pDqGoAxFQJbv+G3s18tjKXyQM8gddy/vDc/KQhnt1LHTBjv3pqRDLPnt6z17pSnYvBXfdtrvGuNCBDjgfzIfh9XrbDXXp53vK/BDuPSQLY0EBvcWxD9xi71FLua6jQSU4R2t1xkCy1yDt4VMXirGDwr+93mRNXEbmAjseZDGLATG6ki0VWjnWLNgea86MrMsIFcQX+bDu6/plwAWAETdt9ftAo1Zs1PDe0eP1Pq29WCMy7HoP/YLd6xbj5IPpXlaJX/VHavuQuKo4mRqy4knYyHTtkO8FbPQG3mwBbpT9OxJOUCigMLsKIh82FDrilVvuLpACy4JUWJs+8EoMy1uCuwFQVm3zSbVFW/pId75FG1KEcw37GyPtoz6yAVDuLYTxzcLdODcVU+j+0TNR5/X6ODWVmM77mCnR6u7ToNBz9e0RtFJWAzX7AhJAT+SfK+VP+szanebUGDVg+Tfo3DLf5+P9Ab/SI6DzlWx+0rAjMvCgTHpxwu2NOO20TK/2m4gw38ub4dvnTe1P0Yb2PkxR5jGT0QCyCnNgMP69lvTc4dmEmnNhoT34AVeAsVO8EBB+wIaCvVW9Hj/2kWAHxwAtbhmotllQ8pTL5h2x0QknrEPGWWfhCuTZ2MqqV5N2g=
  bucket: www.statscraft.org.il
  local_dir: _site
  no_cleanup: true
  skip_cleanup: true
  acl: public_read
  on:
    repo: erikzaadi/statscraft
  region: eu-west-1
  endpoint: www.statscraft.org.il.s3-eu-west-1.amazonaws.com
