name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        # with:
        #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: |
            hugo --minify -b https://www.statscraft.org.il/
            echo wwww.statscraft.org.il > ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          EXTERNAL_REPOSITORY: statscraft/statscraft.github.io
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public